### ISSUE TITLE
rate limit issues

### ISSUE THREAD

**Issue by bryanhpchiang** [ezelikman/parsel#1]
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/98059440/214957232-ab756f6d-9f4c-4f95-9605-67ed3c8a8069.png">

running into some rate limit issues with OAI

is this expected behavior -- i.e. should i ask support to raise my limits?

**Comment by ezelikman** [comment]
Yeah, OAI has unfortunately recently (roughly a month or so) lowered their rate limit for Codex to only 40k tokens/min officially, and it seems like, in practice, it's hard to get even close to that. I'm pretty sure it's worse when there's higher load too. I hope either they fix that or an alternative comes along soon!

**Comment by ezelikman** [comment]
Also, num_completions in consts/py_consts.py is set to 32 by default to make it more likely that any program will work, but you can definitely lower it - I usually used 8 or 16.

**Comment by ezelikman** [comment]
Update: I pushed an update where we don't try the total number of completions by default, instead starting with min_completions, and then doubling until num_completions. This should require fewer calls in general and cause you to hit the rate limit less often. Can't do much else, unfortunately!
